# Generated by Django 5.1.2 on 2024-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nota_matematica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_redacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_geral', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeritoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255)),
                ('nome_diretor', models.CharField(max_length=255)),
                ('nome_escola', models.CharField(max_length=255)),
                ('endereco_escola', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=10)),
                ('media_ensino_medio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
