# Generated by Django 5.1.2 on 2024-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemdata',
            name='cel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enemdata',
            name='celResponsavel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enemdata',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meritoacademico',
            name='cel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='meritoacademico',
            name='celResponsavel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='meritoacademico',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
